### ISSUE TITLE
Lesson5, exercise3.A big cude in Gazebo when capturing features

### ISSUE THREAD

**Issue by sychaichangkun** [udacity/robotics-nanodegree-issues#90] opened 2017-08-03 13:35 UTC
When capturing features in exercise 3, sometimes a big cube would appear and stay still, it's not supposed to be in the model list.

**Comment by ryan-keenan** [comment] 2017-08-03 16:38
Thanks for reporting this!  I haven't seen that behavior myself.  Are you using the VM or local Linux/ROS install?

**Comment by sychaichangkun** [comment] 2017-08-05 13:35
I'm using local Linux+ROS, but a student from live help reported that issue using VM.

**Comment by sahiljuneja** [comment] 2017-08-12 06:05
Is this still an issue? Because we have been unable to reproduce this on the VM as of now to be able to pinpoint what could be causing it.

**Comment by jchernus** [comment] 2017-08-14 18:17
I experience this too.  Running in VM.

**Comment by yuan0623** [comment] 2017-08-28 02:40
I'm experiencing the big cube, what's that?

**Comment by kylesf** [comment] 2017-08-28 21:26
@hvpandya Any idea what the cube may be?

**Comment by hvpandya** [comment] 2017-09-05 18:49
The only two reasons for a cube to appear instead of a given model are:
1) Incorrect GAZEBO_MODEL_PATH in your .bashrc
2) The model file/s are not present at the location you defined as GAZEBO_MODEL_PATH

**Comment by kylesf** [comment] 2017-09-05 18:51
Thanks, Harsh. We will now close this issue.

**Closed as completed by kylesf** 2017-09-05 18:51 UTC
