### ISSUE TITLE
Problems running script follower.py in the Follow Me project

### ISSUE THREAD

**Issue by thatting** [udacity/robotics-nanodegree-issues#161] opened 2017-10-09 12:27 UTC
I have problems running the follower.py script in the Follow Me project (section 6-P-9).  I have renamed the model_weights file (output of simulation) to model_weights.h5 (just added the .h5 extension) and run following line in the RoboND enviroment, after starting the QuadSim simulator and clicking "Follow Me" button + selecting "Spawn People" :  

$ python follower.py model_weights.h5

The python file runs for about 5 seconds then crashes with the Windows message "Python has stopped working".  I am using following versions on my laptop:

Windows (10) operating system

QuadSim simulator :  v1.2.2

Python : 3.5.2 

Also, I've installed as instructed: 

pip install tensorflow==1.2.1
pip install socketIO-client
pip install transforms3d
pip install PyQt5
pip install pyqtgraph

**Comment by danzelmo** [comment] 2017-10-09 13:44
Hmm, that error message sounds scary:) The project has run on multiple windows 10 machines, so that would make me look for a system/build specific problem. 
Here is what I would do.

first: run a helloworld.py type of script from the command line, and make sure this runs. 

second: check if you have multiple different python installs on your system, and that you have the correct version active while running `follower.py`

third:  if you are not getting a stack trace of any kind when running the script. Then I would put an `if False:` about half way down the `if __name__ == '__main__'` section of follower.py, and then indent the rest of the section so it doesn't run. 

I would then adjust the position of this until the line that is causing the problem is found.

**Comment by sahiljuneja** [comment] 2018-04-26 17:36
Closing because of no updates. If this was not resolved then we can reopen this.

**Closed as completed** 2018-04-26 17:36 UTC
